<h1>Hey <?= $user->name ?>!</h1>
<p>Hope you're having a good day today. On the right side of this page is all the sections of this site you can edit. If
    you end up having any problems, please contact John at <a href="mailto:john@jo.mu">john@jo.mu</a>.</p>
<hr/>
<div class="row">
    <div class="col-sm-4 col-lg-4">
        <h4>Settings:</h4>
        <dl>
            <dt>Address</dt>
            <dd><?= $address ?></dd>
            <dt>Email</dt>
            <dd><?= $email ?></dd>
            <dt>Phone</dt>
            <dd><?= $phone ?></dd>
        </dl>
        <hr class="hidden-xs"/>
        <a href="<?= $this->url('admin/config') ?>"><i class="glyphicon glyphicon-edit"></i> Edit</a>
    </div>
    <div class="col-sm-4 col-lg-4">
        <h4>Instructors:</h4>
        <ul class="list-unstyled">
            <?php if ($instructors->count()): ?>
                <?php foreach ($instructors as $instructor): ?>
                    <li>
                        <a href="<?= $this->url('admin/instructor/id/' . $instructor->id()) ?>"><?= $instructor->name ?></a>
                    </li>
                <?php endforeach ?>
            <?php else: ?>
                <li>No instructors added yet.</li>
            <?php endif ?>
        </ul>
        <hr class="hidden-xs"/>
        <a href="<?= $this->url('admin/instructor/id/0') ?>"><i class="glyphicon glyphicon-plus-sign"></i>
            Instructor</a>
    </div>
    <div class="col-sm-4 col-lg-4">
        <h4>News:</h4>
        <ul class="list-unstyled">
            <?php if ($news->count()): ?>
                <?php foreach ($news as $item): ?>
                    <li><a href="<?= $this->url('admin/blog/id/' . $item->id()) ?>"><?= $item->title ?>
                            <small>
                                <time
                                    datetime="<?= date('Y-m-d\TH:i:sa', strtotime($item->created)) ?>"><?= date('F j, Y', strtotime($item->created)) ?></time>
                            </small>
                        </a></li>
                <?php endforeach ?>
            <?php else: ?>
                <li>No news posted yet.</li>
            <?php endif ?>
        </ul>
        <hr class="hidden-xs"/>
        <a href="<?= $this->url('admin/blog/id/0') ?>"><i class="glyphicon glyphicon-plus-sign"></i> Article</a>
    </div>
</div>
<hr class="visible-xs hidden-lg"/>