<div class="page-header">
    <h1><a href="<?= $this->url('admin') ?>">Admin
            Panel</a> &raquo; <?php if (isset($item)): ?><a href="<?= $this->url('admin/schedule') ?>">
                Schedule</a> &raquo; <?php if ($item->exists()): ?>Editing <?= $this->clean($item->getClassName()) ?><?php else: ?>New Class<?php endif ?><?php else: ?>Schedule
        <a href="<?= $this->url('admin/schedule/id/0') ?>">
                <small><i class="glyphicon glyphicon-plus-sign"></i></small></a><?php endif ?>
    </h1>
</div>