<?php
    /**
     * Phyneapple!
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@phyneapple.com so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\Phyneapple
     * @copyright Copyright (c) 2013 Phyneapple! (http://www.phyneapple.com/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $collection \PHY\Model\Schedule\Collection
     */
?>
<?php $days = \PHY\Model\Schedule::getDays() ?>
<?php $time = function ($time) {
    $hoursFrom = explode('.', (string)$time);
    if (count($hoursFrom) > 1) {
        $minutesFrom = str_pad(round(60 * $hoursFrom[1] / 100), 2, '0');
    } else {
        $minutesFrom = '00';
    }
    $hoursFrom = $hoursFrom[0];
    if ($hoursFrom >= 12) {
        $from = ($hoursFrom > 12
                ? $hoursFrom - 12
                : $hoursFrom) . ':' . $minutesFrom . 'pm';
    } else {
        $from = (!$hoursFrom
                ? 12
                : $hoursFrom) . ':' . $minutesFrom . 'am';
    }
    return $from;
} ?>
<?php $tag = $this->tag() ?>
<?php $i = 0 ?>
    <?= $this->child('message') ?>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Day</th>
            <th>Starts</th>
            <th>Ends</th>
            <th>Title</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php if (count($collection)): ?>
            <?php foreach ($collection as $item): ?>
                <tr class="schedule-<?= $item->id() ?>">
                    <td class="schedule-<?= $item->id() ?>-day"><?= $this->clean($days[$item->day]); ?></td>
                    <td class="schedule-<?= $item->id() ?>-start"><?= $this->clean($time($item->start)); ?></td>
                    <td class="schedule-<?= $item->id() ?>-end"><?= $this->clean($time($item->end + .25)); ?></td>
                    <td class="schedule-<?= $item->id() ?>-title"><?= $this->clean($item->title); ?></td>
                    <td class="action"><?= $tag->helper()->url('Edit', '/admin/schedule/id/' . $item->id()) ?></td>
                    <td class="action">
                        <?=
                            $tag->helper()->url('Remove', '/admin/schedule/id/' . $item->id(), [
                                'class' => 'ajax',
                                'data' => [
                                    'method' => 'delete',
                                    'confirm' => 'remove',
                                    'message' => 'Are you sure you want to remove ' . $this->clean($item->getClassName()) . '?',
                                    'type' => 'confirm',
                                    'element' => '.schedule-' . $item->id()
                                ]
                            ])?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="5">No classes are scheduled yet. <a href="<?= $this->url('admin/schedule/id/0') ?>"
                                                                 class="btn btn-sm btn-primary">Add</a>
                </td>
            </tr>
        <?php endif ?>
        </tbody>
    </table>
    <?= $this->child('pagination') ?>