<?php
    /**
     * Phyneapple!
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@phyneapple.com so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\Phyneapple
     * @copyright Copyright (c) 2013 Phyneapple! (http://www.phyneapple.com/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     */
?>
<footer>
    <hr/>
    <ul class="text-muted list-inline pull-left">
        <li><?=
                isset($copyright)
                    ? $copyright
                    : 'Ha Ha No Site Name! Suck It!' ?></li>
        <li><a href="<?= $this->url('contact') ?>">Contact</a></li>
        <li><a href="https://www.facebook.com/briggsmma">Facebook</a></li>
    </ul>
    <div class="pull-right">
        <ul class="list-inline">
            <li><img alt="Zenith"
                     src="<?= $this->url('zenith.jpg', 'image') ?>"/>
            </li>
            <li><img alt="CSW Combat Submission Wrestling"
                     src="<?= $this->url('csw.jpg', 'image') ?>"/>
            </li>
            <li><a href="http://www.drysdalebjj.com/" rel="nofollow"><img alt="Drysdale BJJ"
                                                                          src="<?= $this->url('drysdale.jpg', 'image') ?>"/></a>
            </li>
        </ul>
        <ul class="list-inline">
            <li><img alt="STX Kickboxing"
                     src="<?= $this->url('stx.jpg', 'image') ?>"/>
            </li>
        </ul>
    </div>
</footer>
<?php
    if (isset($js)):
        $tag = $this->tag();
        foreach ($js as $file):
            echo $tag->script->attributes($file);
        endforeach;
    endif
?>
<script type="text/javascript">try {
        if (typeof console !== 'undefined' && typeof console.log !== 'undefined')console.log('Generation: <?=$app->getDebugger()->profile()?>')
    } catch (e) {
    }</script>