<div class="page-header">
    <h1><a href="<?= $this->url('admin') ?>">Admin
            Panel</a> &raquo; <?php if (isset($item)): ?><a href="<?= $this->url('admin/testimonial') ?>">
                Testimonials</a> &raquo; <?php if ($item->exists()): ?>Editing <?= $this->clean($item->title) ?><?php else: ?>New Testimonial<?php endif ?><?php else: ?>Testimonials
        <a href="<?= $this->url('admin/testimonial/id/0') ?>">
                <small><i class="glyphicon glyphicon-plus-sign"></i></small></a><?php endif ?>
    </h1>
</div>