<?php
    /**
     * Phyneapple!
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@phyneapple.com so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\Phyneapple
     * @copyright Copyright (c) 2013 Phyneapple! (http://www.phyneapple.com/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $item \PHY\Model\Testimonial
     */
?>
<form action="<?= $_SERVER['REQUEST_URI'] ?>" class="form" method="post">
    <?= $this->child('message'); ?>
    <div class="row">
        <div class="col-sm-6 col-lg-6">
            <div class="form-group">
                <label for="testimonial-title" class="control-label">Title</label>
                <input id="testimonial-title" class="form-control" name="testimonial[title]" type="text"
                       value="<?= $this->clean($item->title) ?>"/>
            </div>
            <div class="form-group">
                <label for="testimonial-name" class="control-label">Author's Name</label>
                <input id="testimonial-name" class="form-control" name="testimonial[name]" type="text"
                       value="<?= $this->clean($item->name) ?>"/>
            </div>
        </div>
        <div class="col-sm-6 col-lg-6">
            <div class="form-group">
                <label for="testimonial-email" class="control-label">Author's Email</label>
                <input id="testimonial-email" class="form-control" name="testimonial[email]" type="email"
                       value="<?= $this->clean($item->email) ?>"/>
            </div>
            <div class="form-group">
                <label for="testimonial-url" class="control-label">Author's Website</label>
                <input id="testimonial-url" class="form-control" name="testimonial[url]" type="url"
                       value="<?= $this->clean($item->url) ?>"/>
            </div>
        </div>
    </div>
    <hr/>
    <div class="form-group">
        <label for="testimonial-content" class="control-label">Content</label>
        <textarea class="form-control" id="testimonial-content" name="testimonial[content]" rows="20"
                  cols="30"><?= $this->clean($item->content) ?></textarea>
    </div>
    <hr/>
    <div class="form-group">
        <button class="btn btn-primary">Save</button>
    </div>
</form>