<div class="page-header">
    <h1><a href="<?= $this->url('admin') ?>">Admin
            Panel</a> &raquo; <?php if (isset($item)): ?><a href="<?= $this->url('admin/instructor') ?>">
                Instructors</a> &raquo; <?php if ($item->exists()): ?>Editing <?= $this->clean($item->name) ?><?php else: ?>New Instructor<?php endif ?><?php else: ?>Instructors
        <a href="<?= $this->url('admin/instructor/id/0') ?>">
                <small><i class="glyphicon glyphicon-plus-sign"></i></small></a><?php endif ?>
    </h1>
</div>