<?php
    /**
     * Phyneapple!
     *
     * LICENSE
     *
     * This source file is subject to the Open Software License (OSL 3.0)
     * that is bundled with this package in the file LICENSE.txt.
     * It is also available through the world-wide-web at this URL:
     * http://opensource.org/licenses/osl-3.0.php
     * If you did not receive a copy of the license and are unable to
     * obtain it through the world-wide-web, please send an email
     * to license@phyneapple.com so we can send you a copy immediately.
     *
     * @package PHY
     * @category PHY\Phyneapple
     * @copyright Copyright (c) 2013 Phyneapple! (http://www.phyneapple.com/)
     * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
     * @author John Mullanaphy <john@jo.mu>
     *
     * @var $this \PHY\View\Block
     * @var $collection \PHY\Model\Closing\Collection
     */
?>
<?php $tag = $this->tag() ?>
    <?= $this->child('message') ?>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Date</th>
            <th>Title</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php if (count($collection)): ?>
            <?php foreach ($collection as $item): ?>
                <tr class="closing-<?= $item->id() ?>">
                    <td class="closing-<?= $item->id() ?>-date"><?= $this->clean(date('Y-m-d', strtotime($item->date))) ?></td>
                    <td class="closing-<?= $item->id() ?>-title"><?= $this->clean($item->title) ?></td>
                    <td class="action"><?= $tag->helper()->url('Edit', '/admin/closing/id/' . $item->id()) ?></td>
                    <td class="action">
                        <?=
                            $tag->helper()->url('Remove', '/admin/closing/id/' . $item->id(), [
                                'class' => 'ajax',
                                'data' => [
                                    'method' => 'delete',
                                    'confirm' => 'remove',
                                    'message' => 'Are you sure you want to remove ' . $this->clean($item->key) . '?',
                                    'type' => 'confirm',
                                    'element' => '.closing-' . $item->id()
                                ]
                            ])?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="4">No closings are scheduled yet. <a href="<?= $this->url('admin/closing/id/0') ?>"
                                                                  class="btn btn-sm btn-primary">Add</a>
                </td>
            </tr>
        <?php endif ?>
        </tbody>
    </table>
    <?= $this->child('pagination') ?>